### ISSUE TITLE
Open options page instead of extracted links page

### ISSUE THREAD

**Issue by wogam** [cssnr/link-extractor#82]
As per title, whenever using any filter or even trying to extract all domains. Happens from context menu, keyboard shortcut and from icon. It was working two weeks ago. Firefox 127, tried latest version (0.7) and 0.6.1

**Comment by smashedr** [comment]
Have you tried granting host permissions to the extension?

The only reason extracting links will take you to the options page, is if you are attempting to extract links from a page that you do not have host permissions for.

Opening the popup and using the right-click context menu should grant permissions for the current page. So if granting host permissions fixes this, then there may be a deeper underlying issue. 

You can also open the console for the current page (Ctrl+Shift+I) and you should get more details as to why the links are not extracting.

**Comment by smashedr** [comment]
Did you ever get this issue sorted out? If you are still having troubles let me know and I will try my best to help out. Otherwise, going to close this out. Thanks again for making the report.

**Comment by smashedr** [comment]
The latest version now takes you to a permissions page with the exact error message prevented the extraction vs opening the options page. So this issue/behavior should now be fixed. Please let us know if are having any issues.
